export interface ServerToClientEvents {
    'new-message': (message: import('./common').Message) => void;
    'message-deleted': (data: { messageId: string }) => void;
    'message-updated': (data: { messageId: string; updatedMessage: import('./common').Message }) => void;
    'message-edited': (data: { messageId: string; newText: string; edited: boolean; editedAt: string; embed?: import('./common').Embed }) => void;
    'message-reaction-updated': (data: { messageId: string; reactions: Record<string, string[]> }) => void;
    'message-pinned': (data: { roomId: string; pinnedMessage: any }) => void;
    'message-unpinned': (data: { roomId: string; messageId: string }) => void;
    'pinned-messages-list': (data: { roomId: string; pinnedMessages: any[] }) => void;
    'messages-read-status': (data: Array<{ id: string; readBy: string[] }>) => void;
    'user-speaking-state': (data: { userId: string; speaking: boolean; timestamp: number }) => void;
    'user-presence-change': (data: { userId: string; state: string }) => void;
    'user-joined': () => void;
    'user-left': (data: { userId: string }) => void;
    'existing-producers': (data: { producers: any[] }) => void;
    'consumerParameters': (data: any) => void;
    'producerPaused': (data: { producerId: string; peerId: string }) => void;
    'producerResumed': (data: { producerId: string; peerId: string }) => void;
    'new-producer': (data: { producerId: string; clientID: string; userId: string }) => void;
    'producer-closed': (data: { producerId: string }) => void;
    'mic-indicator-update': (data: { userId: string; isActive: boolean }) => void;
    'room-mode-updated': (data: { roomId: string; imagesOnly?: boolean; readOnly?: boolean }) => void;
    'room-participants-updated': (data: { online: any[]; offline: any[] }) => void;
    'room-participants': (data: any[]) => void;
    'room-snapshot': (data: any) => void;
    'join-ack': (data: { success: boolean }) => void;
    'unread-update': (data: { serverId: string; roomId: string; count: number; hasMention: boolean; personalCount: number }) => void;
    'live-notification': (data: any) => void;
    'personal-notification': (data: any) => void;
    'init-secondary-chat': (data: { roomId: string }) => void;
    'poll:updated': (data: any) => void;
    'poll:closed': (data: { roomId: string; pollId: string }) => void;
    'request-client-diagnostic': (data: { roomId: string }) => void;
    'diagnostic-update': (data: any) => void;
    'error': (error: Error) => void;
    'connect': () => void;
    'disconnect': (reason: string) => void;
    'note:created': (data: any) => void;
    'note:updated': (data: any) => void;
    'note:deleted': (data: any) => void;
    'note:reaction': (data: any) => void;
    'note:thread:message': (data: any) => void;
    'ice-restart-result': () => void;
    'console-command': (data: { text: string; senderName: string; senderId: string }) => void;
}

export interface ClientToServerEvents {
    'join-room': (data: { roomId: string }) => void;
    'leave-room': (data: { roomId: string }) => void;
    'join-text-room': (data: { roomId: string }) => void;
    'leave-text-room': (data: { roomId: string }) => void;
    'send-message': (data: any) => void;
    'toggle-reaction': (data: { messageId: string; emoji: string; roomId: string }) => void;
    'edit-message': (data: any, callback?: (response: any) => void) => void;
    'delete-message': (data: any, callback?: (response: any) => void) => void;
    'request-message-history': (data: any, callback?: (response: any) => void) => void;
    'transport-connect': (data: any, callback?: (response: any) => void) => void;
    'produce': (data: any, callback?: (response: any) => void) => void;
    'consume': (data: any, callback?: (response: any) => void) => void;
    'restart-ice': (data: any, callback?: (response: any) => void) => void;
    'new-producer-notification': (data: any) => void;
    'mic-indicator-state': (data: any) => void;
    'producerPaused': (data: any) => void;
    'producerResumed': (data: any) => void;
    'request-mic-states': (data: { roomId: string }) => void;
    'request-room-snapshot': (data: { roomId: string }, callback?: (response: any) => void) => void;
    'pin-message': (data: any, callback?: (response: any) => void) => void;
    'unpin-message': (data: any, callback?: (response: any) => void) => void;
    'get-pinned-messages': (data: any, callback?: (response: any) => void) => void;
    'forward-message': (data: any) => void;
    'create-poll': (data: any) => void;
    'poll:vote': (data: any) => void;
    'poll:close': (data: any) => void;
    'fetch-message-embed': (data: any) => void;
    'secondary-chat-update': (data: { roomId: string }) => void;
    'secondary-chat-close': () => void;
    'start-room-diagnostic': (data: { roomId: string }) => void;
    'stop-room-diagnostic': (data: { roomId: string }) => void;
    'client-diagnostic-response': (data: any) => void;
    'ping': () => void;
}
